const districts = [
  { value: "সকল", label: "সকল" },
  { value: "বাগেরহাট", label: "বাগেরহাট" },
  { value: "বান্দরবান", label: "বান্দরবান" },
  { value: "বড়গুনা", label: "বড়গুনা" },
  { value: "বরিশাল", label: "বরিশাল" },
  { value: "বগুড়া", label: "বগুড়া" },
  { value: "ভোলা", label: "ভোলা" },
  { value: "ব্রাহ্মণবাড়িয়া", label: "ব্রাহ্মণবাড়িয়া" },
  { value: "চাঁদপুর", label: "চাঁদপুর" },
  { value: "চাঁপাইনবাবগঞ্জ", label: "চাঁপাইনবাবগঞ্জ" },
  { value: "চট্টগ্রাম", label: "চট্টগ্রাম" },
  { value: "চুয়াডাঙ্গা", label: "চুয়াডাঙ্গা" },
  { value: "কুমিল্লা", label: "কুমিল্লা" },
  { value: "কক্সবাজার", label: "কক্সবাজার" },
  { value: "ঢাকা", label: "ঢাকা" },
  { value: "দিনাজপুর", label: "দিনাজপুর" },
  { value: "ফরিদপুর", label: "ফরিদপুর" },
  { value: "ফেনী", label: "ফেনী" },
  { value: "গাইবান্ধা", label: "গাইবান্ধা" },
  { value: "গাজীপুর", label: "গাজীপুর" },
  { value: "গোপালগঞ্জ", label: "গোপালগঞ্জ" },
  { value: "হবিগঞ্জ", label: "হবিগঞ্জ" },
  { value: "জামালপুর", label: "জামালপুর" },
  { value: "যশোর", label: "যশোর" },
  { value: "ঝালকাঠি", label: "ঝালকাঠি" },
  { value: "ঝিনাইদহ", label: "ঝিনাইদহ" },
  { value: "জয়পুরহাট", label: "জয়পুরহাট" },
  { value: "খাগড়াছড়ি", label: "খাগড়াছড়ি" },
  { value: "খুলনা", label: "খুলনা" },
  { value: "কিশোরগঞ্জ", label: "কিশোরগঞ্জ" },
  { value: "কুষ্টিয়া", label: "কুষ্টিয়া" },
  { value: "কুড়িগ্রাম", label: "কুড়িগ্রাম" },
  { value: "লক্ষ্মীপুর", label: "লক্ষ্মীপুর" },
  { value: "লালমনিরহাট", label: "লালমনিরহাট" },
  { value: "মাদারীপুর", label: "মাদারীপুর" },
  { value: "মাগুরা", label: "মাগুরা" },
  { value: "মানিকগঞ্জ", label: "মানিকগঞ্জ" },
  { value: "মেহেরপুর", label: "মেহেরপুর" },
  { value: "মৌলভীবাজার", label: "মৌলভীবাজার" },
  { value: "মুন্সিগঞ্জ", label: "মুন্সিগঞ্জ" },
  { value: "ময়মনসিংহ", label: "ময়মনসিংহ" },
  { value: "নওগাঁ", label: "নওগাঁ" },
  { value: "নড়াইল", label: "নড়াইল" },
  { value: "নারায়ণগঞ্জ", label: "নারায়ণগঞ্জ" },
  { value: "নরসিংদী", label: "নরসিংদী" },
  { value: "নেত্রকোণা", label: "নেত্রকোণা" },
  { value: "নীলফামারী", label: "নীলফামারী" },
  { value: "নোয়াখালী", label: "নোয়াখালী" },
  { value: "পাবনা", label: "পাবনা" },
  { value: "পঞ্চগড়", label: "পঞ্চগড়" },
  { value: "পটুয়াখালী", label: "পটুয়াখালী" },
  { value: "পিরোজপুর", label: "পিরোজপুর" },
  { value: "রাজবাড়ী", label: "রাজবাড়ী" },
  { value: "রাজশাহী", label: "রাজশাহী" },
  { value: "রাঙামাটি", label: "রাঙামাটি" },
  { value: "রংপুর", label: "রংপুর" },
  { value: "সাতক্ষীরা", label: "সাতক্ষীরা" },
  { value: "শরীয়তপুর", label: "শরীয়তপুর" },
  { value: "শেরপুর", label: "শেরপুর" },
  { value: "সিরাজগঞ্জ", label: "সিরাজগঞ্জ" },
  { value: "সুনামগঞ্জ", label: "সুনামগঞ্জ" },
  { value: "সিলেট", label: "সিলেট" },
  { value: "টাঙ্গাইল", label: "টাঙ্গাইল" },
  { value: "ঠাকুরগাঁও", label: "ঠাকুরগাঁও" },
];

const bloodGroups = [
  { value: "A+", label: "A+" },
  { value: "A-", label: "A-" },
  { value: "B+", label: "B+" },
  { value: "B-", label: "B-" },
  { value: "O+", label: "O+" },
  { value: "O-", label: "O-" },
  { value: "AB+", label: "AB+" },
  { value: "AB-", label: "AB-" },
];
const relations = [
  { value: "মা", label: "মা" },
  { value: "বাবা", label: "বাবা" },
  { value: "ভাই", label: "ভাই" },
  { value: "বোন", label: "বোন" },
  { value: "কাজিন", label: "কাজিন" },
  { value: "বন্ধু", label: "বন্ধু" },
  { value: "অন্যান্য", label: "অন্যান্য" },
];

const genders = [
  { value: "Male", label: "পুরুষ" },
  { value: "Female", label: "মহিলা" },
];

export { districts, bloodGroups, relations, genders };
